title: La Confrérie du Cube
logo:
description: Archives des découvertes Archéologiques sur cette confrérie.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  -Le_Traité_des_Factions.md
