name: publish to github wiki

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Upload Release Notes to Wiki
      uses: docker://decathlon/wiki-page-creator-action:2.0.1
      env:
        GH_PAT: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
        ACTION_MAIL: myuser@users.noreply.github.com
        ACTION_NAME: myPushingUser
        OWNER: la-confrérie-du-cube
        REPO_NAME: lore
        MD_FOLDER: docs
        SKIP_MD: README.md 
